### PR TITLE
Add rust_link, a Rust replacement for vlink & tlink

### PR DESCRIPTION
**Pull request by jonjensen**
Why? To do the same thing vlink and tlink do, without a compiled-in socket address and thus one compiled program can be used for multiple Interchange daemons. It has speed similar to C but in Rust, a memory-safe language, for less risky customization.

Supports both UNIX & INET sockets, including host name resolution for INET sockets.

It retries after failed connection attempts similar to vlink/tlink, but every half-second for up to 10 seconds vs. vlink/tlink every second up to 30 seconds. (Of course you can customize before you compile.) This is to reduce CGI process pile-up when the Interchange server is down or overloaded.

The 503 error page HTML is in its own file for easy customizing.

See README.md for more information.

### CODE REVIEW

**Comment by pajamian** [comment]
On 3/03/23 18:55, Jon Jensen wrote:
> Why? To do the same thing vlink and tlink do, without a compiled-in 
> socket address and thus one compiled program can be used for multiple 
> Interchange daemons.

The existing vlink and tlink programs already support this by setting 
the MINIVEND_SOCKET or MINIVEND_PRT environment variables accordingly. 
I use this feature already for multi-instance support in the interchange 
packages that I release for RHEL-derived distros.


Peter

**Comment by jonjensen** [comment]
@pajamian Sorry, I didn't explain myself very well. I know they do, because I used the same environment variable names on purpose to be compatible. (Otherwise I would never use MiniVend in a name.)

At the time I started writing this, you had not yet added that feature (2020-06-28), so it was in impetus back then. Now it's just parity.

**Comment by pajamian** [comment]
On 4/03/23 14:14, Jon Jensen wrote:
> @pajamian <https://github.com/pajamian> Sorry, I didn't explain myself 
> very well. I know they do, because I used the same environment variable 
> names on purpose to be compatible. (Otherwise I would never use MiniVend 
> in a name.)
> 
> At the time I started writing this, you had not yet added that feature 
> (2020-06-28), so it was in impetus back then. Now it's just parity.

That makes sense.  The feature has actually been documented for at least 
the past 24 years in compile_link.PL, but it appears only partially 
implemented, so I just fixed it to work properly like the docs say it 
should, hence the MINIVEND names.

https://github.com/interchange/interchange/blame/master/scripts/compile_link.PL#L384


Peter

**Review by msjohns1 — APPROVED** [review]
Not familiar with Rust, but looks good to me.

**Pull request merged**
